Table people {
  id int [pk]
  first_name text
  last_name text
  career text
  mobile text 
  email text
  address text
  dob timestamp
}

Table strengths {
  id int 
  person_id int [ref: > people.id]
  description text
}

Table pressure_points {
  id int
  person_id int [ref: > people.id]
  description text
}

Table attendees {
  attendee_id int [ref: > people.id]
  event_id int [ref: > events.id]
}

Table notes {
  id int
  person_id int [ref: > people.id]
  text text
}

Table events {
  id int [pk]
  event_description text
  notes text
  date timestamp
}

Table relationship {
  person_one_id int [ref: > people.id]
  person_two_id int [ref: > people.id]
  relationship_type text
}